# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Jin-Young Kim
# title: Dr
email: jeremy@twelvelabs.io
# email_title: Email (Email title override)
# phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
website: https://github.com/seahl0119
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: never

# Social links
# twitter_username: jekyllrb
github_username:  seahl0119
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: profile.php?id=100009180653823
# flickr_username: jekyll
# instagram_username: jekyll
linkedin_username: jin-young-kim-4326a2233
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
orcid_username: 0000-0001-9691-877X
googlescholar_username: 7VupJX4AAAAJ

# # Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# # - title: another link
# #   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
# #   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
      J.-Y. Kim received a BS degree in mathematics and computer science from Yonsei University, Seoul, South Korea, in 2018. He is currently pursuing a Ph.D. degree at the Department of Computer Science, Yonsei University. 
      His current research interests include neural networks, artificial intelligence, and controllable representation learning.

      <strong> Research interest <strong>
      - Deep learning; diffusion model
      - Representation learning
      - Generative model
      - Video foundation model
      
# You can even add paragraphs by using empty lines like this and add anything else [markdown](https://www.markdownguide.org/getting-started#what-is-markdown) supports such as
#   - Lists
#   - Tables
#   - <a href="google.com">Links</a>
#   - Images ![alt text](/images/landscape-trees.jpg "Trees")

content:
          
  - title: ACADEMIC BACNKGROUND 
    layout: list
    content:
      - layout: left
        title: Twelvelabs
        sub_title: ML Research Scientist
        caption: 2023.10 - present
        link: https://www.twelvelabs.io/
        # quote: >
        #   Short description of the company (optional)
        # description: | # this will include new lines to allow paragraphs
        #   Description of role
        
      - title: Riiid Inc.
        sub_title: Senior AI Research Scientist
        caption: 2023.02- 2023.10
        # link: https://www.twelvelabs.io/
        
      - title: Riiid Inc.
        sub_title: AI Research Scientist
        caption: 2022.04-2023.02 
        # link: https://www.twelvelabs.io/
                
      - title: Yonsei University, Korea
        sub_title: M. S. & Ph. D. Combined course student in Computer Science
        caption: 2018 - (GPA \U+003A  4.16 / 4.30) 
        # link: https://www.twelvelabs.io/
                
      - title: Yonsei University, Korea
        sub_title: B.S. in Mathematics
        caption: 2014.03 - 2018.02 (GPA \U+003A 3.59 / 4.30) 
                
      - title: Yonsei University, Korea
        sub_title: B.S. in Computer Science
        caption: 2014.03 - 2018.02 (GPA \U+003A 3.59 / 4.30) 


        
  - title: ACADEMIC EXPERIENCE 
    layout: text
    content: | # this will include new lines to allow paragraphs
      Introduction to Artificial Intelligence: Methods, Models, Algorithms, Int. Summer University 2018,  Higher School of Economics, 2018. 



        
  - title: PUBLICATIONS
    layout: text
    content: | # this will include new lines to allow paragraphs
     - Twelvelabs, “Pegasus-v1 Technical Report,” arXiv preprint, 2024.  
     - J. Y. Kim &#42;, H. Go &#42;, S. Kwon, and H. G. Kim, “Denoising Task Difficulty-based Curriculum for Training Diffusion Models,” arXiv preprint, 2024.  (*Denotes equal contribution)  <br>
     - B. Park, H. Go, J. Y. Kim, S. Woo, S. Ham, and C. Kim, “Switch Diffusion Transformer: Synergizing Denoising Tasks with Sparse Mixture-of-Experts,” arXiv preprint, 2024. <br>
     - S. Woo*, B. Park*, H. Go, J. Y. Kim, and C. Kim, “HarmonyView: Harmonizing Consistency and Diversity in One-Image-to-3D,” IEEE/CVF Conference on Computer Vision and Pattern Recognition (CVPR), 2024. (*Denotes equal contribution)  <br>
     - B. Park*, S. Woo*, H. Go*, J. Y. Kim*, C. Kim, “Denoising Task Routing for Diffusion Models,” International Conference on Learning Representations (ICLR), 2024. (*Denotes equal  contribution)  <br>
     - S. Kwon*, S. Kim*, S. Lee, J. Y. Kim, S. An, and K. Kim, “Addressing Selection Bias in Computerized Adaptive Testing: A User-Wise Aggregate Influence Function Approach,” International Conference on Information & Knowledge Management (CIKM), 2024. (*Denotes equal  contribution)  <br>
     - Y. Lee*, J. Y. Kim*, H. Go*, M Jeong, S. Oh, and S. Choi, “Multi-Architecture Multi-Expert Diffusion  Models,” AAAI Conference on Artificial Intelligence (AAAI), 2024. (*Denotes equal  contribution)  <br>
     - J. Y. Kim*, S. Kwon*, H. Go*, Y. Lee, and S. Choi, “ScoreCL: Augmentation-Adaptive Contrastive  Learning via Score-Matching Function,” arXiv preprint, 2024.  (*Denotes equal contribution)  <br>
     - H. Go*, J. Y. Kim*, Y. Lee, S. Lee, S. Oh, H. Moon, and S. Choi, “Addressing Negative Transfer in  Diffusion Models,” Advances in Neural Information Processing Systems (NeurIPS), 2024. (*Denotes equal contribution)  <br>
     - H. Go*, Y. Lee*, J. Y. Kim*, S. Lee, M. Jeong, H. S. Lee, and S. Choi, “Towards Practical Plug-and-Play  Diffusion Models”, IEEE/CVF Conference on Computer Vision and Pattern Recognition (CVPR), 2023. (*Denotes equal contribution)  <br>
     - J. Y. Kim and S. B. Cho, “Predicting Residential Energy Consumption by Explainable Deep Learning with  Long-term and Short-term Latent Variables,” Cybernetics and Systems, vol. 54, no. 3, pp. 270-285, 2023.  (SCIE) (IF: 1.879)  <br>
     - J. Park, J. Y. Kim, S. Kwon, and S. W. Lee, “SAICL: Student Modelling with Interaction-level Auxiliary  Contrastive Tasks for Knowledge Tracing and Dropout Prediction”, arXiv preprint arXiv:2210.09012,  2022.  <br>
     - J. Y. Kim and S. B. Cho, “An Information Theoretic Approach to Reducing Algorithmic Bias for Machine  Learning,” Neurocomputing, vol. 500, pp. 26-38, 2022. (SCIE) (IF: 5.719)  <br>
     - H.-J. Moon, J. Y. Kim and S. B. Cho, “Graph Classification Method based on Partitioning Algorithm  through Graph Partial Information Extraction,” Proc. of Korea Software Congress, 2021.  (In Korean) <br>
     - K.-W. Park, J. Y. Kim and S. B. Cho, “Genetic Optimization-based Logical Integration of Subgraph Embedding for Graph Classification,” Proc. of Korea Software Congress, 2021. (In Korean) <br>
     - J. Y. Kim and S.-B. Cho, “Obfuscated Malware Detection Using Deep Generative Model based on  Global/Local Features,” Computers & Security, pp. 102501, 2022. (SCIE) (IF: 4.438)  <br>
     - J. Y. Kim and S.-B. Cho, “Explainable Prediction of Electric Energy Demand Using a Deep Autoencoder  with Interpretable Latent Space,” Expert Systems with Applications, vol. 186, pp. 115842, 2021. (SCIE)  (IF: 6.954)  <br>
     - G.-B. Jang, J.-Y. Kim and S.-B. Cho, "Cross-Domain Fault Diagnosis of Rotating Machinery Using  Discriminative Feature Attention Network," IEEE Access, vol. 9, pp. 99781 - 99793, 2021. (SCIE) (IF:  3.367)  <br>
     - J.-Y. Kim and S.-B. Cho, "A Systematic Analysis and Guidelines of Graph Neural Networks for Practical  Applications," Expert Systems with Applications, 2021. (SCIE) (IF: 6.954)   <br>
     - S.-B. Cho and J.-Y. Kim, "Clustered embedding using deep learning to analyze urban mobility based on  complex transportation data," PLoS one, vol. 16, no. 4, pp. e0249318, 2021. (SCIE) (IF: 3.240)  <br>
     - J. Y. Kim and S. B. Cho, “Deep CNN Transferred from VAE and GAN for Classifying Irritating Noise in  Automobile,” Neurocomputing, 2021. (SCIE)(IF: 5.719)   <br>
     - J. Y. Kim and S. B. Cho, “A Deep Neural Network Ensemble of Multimodal Signals for Classifying  Excavator Operations,” Neurocomputing, 2021. (SCIE)(IF: 5.719)  <br>
     - H.-J. Moon, J. Y. Kim and S. B. Cho, “Graph Pattern Detection Methods Using Subgraph Segmentation  based on Internode Relationship Inference,” Proc. of Korea Software Congress, 2020. (In Korean)  <br>
     - D.-W. Park, J. Y. Kim and S. B. Cho, “A Model to Debias Word Embedding Using Adversarial Autoencoder  for Reducing Bias in Abusive Sentences Classification,” Proc. of Korea Software Congress, 2020. (In  Korean)  <br>
     - H.-B. Kang, J. Y. Kim and S. B. Cho, “A Method to Debias Extracted Latent Vector via Adversarial  Autoencoder for Mitigating Age-based Bias in Facial Emotion,” Proc. of Korea Software Congress, 2020.  (In Korean)  <br>
     - J.-Y. Kim and S.-B. Cho, "Electric Energy Demand Forecasting with Explainable Time-series Modeling,"  Int. Conf. on Data Mining Workshop: BigData4SmartEnergy, 2020.   <br>
     - J. Y. Kim and S. B. Cho, “One-class Adversarial Learning Method for Frame-level Video Anomaly  Detection,” KIISE Trans. on Computing Practices (KTCP), vol. 26, no. 8, pp. 362-366, 2020. (In Korean)  <br>
     - J. Y. Kim and S. B. Cho, “Analysis on Mutual Information for Adversarial Autoencoder to Reduce AI  Algorithmic Bias,” Proc. of Korea Computer Congress, 2020. (In Korean)  <br>
     - K.-H. Lim, J.-Y. Kim and S.-B. Cho, "Generative Adversarial Network with Guided Generator for Non stationary Noise Cancelation," The 15th International Conference on Hybrid Artificial Intelligent Systems,  2020.  <br>
     - J.-Y. Kim and S.-B. Cho, "Interpretable Deep Learning with Hybrid Autoencoders to Predict Electric  Energy Consumption," Int. Workshop on Soft Computing Models in Industrial and Environmental  Applications, 2020  <br>
     - J.-Y. Kim and S.-B. Cho, “Fair Representation for Safe Artificial Intelligence via Adversarial Learning of  Unbiased Information Bottleneck.,” AAAI Conf. on Artificial Intelligence Workshop: SafeAI, 2020.  <br>
     - K.-H. Lim, J.-Y. Kim and S.-B. Cho, “GAN with dual discriminator for non-stationary noise cancellation,”  Proc. of Korea Software Congress, 2019. (In Korean)  <br>
     - W.-S. Shin, J.-Y. Kim and S.-B. Cho, “GAN-based noise elimination model for high-quality speech  database,” Proc. of Korea Software Congress, 2019. (In Korean)  <br>
     - T.-Y. Kong, J.-Y. Kim and S.-B. Cho, “Attention-based convolutional autoencoder for speech separation,”  Proc. of Korea Software Congress, 2019. (In Korean)  <br>
     - K.-H. Min, J.-Y. Kim and S.-B. Cho, “Algorithmic bias mitigation method via controlling latent space  regards to protected features,” Proc. of Korea Software Congress, 2019. (In Korean)  <br>
     - J. Y. Kim, K. H. Lim, and S. B. Cho, “Personalized POI Embedding for Successive POI Recommendation with Large-scale Smart Card Data,” IEEE Int. Conf. on Big Data, 2019.   <br>
     - J. Y. Kim and S. B. Cho, “Unsupervised Novelty Detection in Video with Adversarial Autoencoder based  on Non-Euclidean Space,” Int. Conf. on Signal Image Technology & Internet based Systems, 2019.  <br>
     -  K. H. Min, J. Y. Kim, and S. B. Cho, “Systematic Performance Evaluation of AI Algorithmic Bias  Mitigation via Adversarial Autoencoder,” Korean Institute of Intelligent Systems Fall Conf., 2019. (In Korean)  <br>
     - E. B. Lee, J. Y. Kim, and S. B. Cho, “Performance Evaluation of Unsupervised Adversarial Learning for  Frame-level Video Anomaly Detection,” Korean Institute of Intelligent Systems Fall Conf., 2019.  (In Korean)  <br>
     - J. Y. Kim and S. B. Cho, “Conditioned Generative Model via Latent Semantic Controlling for Learning  Deep Representation of Data,” Int. Conf. on Intelligent Data Engineering and Automated Learning  (IDEAL), 2019.   <br>
     - K. H. Lim, J. Y. Kim, and S. B. Cho, “Non-stationary Noise Cancellation Using Deep Autoencoder based  on Adversarial Learning,” Int. Conf. on Intelligent Data Engineering and Automated Learning (IDEAL), 2019.  <br>
     - J. Y. Kim and S. B. Cho, “A Method of Frame-Level Video Anomaly Detection with Unsupervised  Adversarial Learning,” Korea Computer Congress (KCC), pp. 999-101, 2019. (In Korean) <br>
     - J. Y. Kim and S. B. Cho, “Deep Learning Model based on Autoencoder for Reducing Algorithmic Bias of  Gender,” Journal of KIISE, vol. 46, no. 8, pp. 721-725, 2019.  (In Korean) <br>
     - J. Y. Kim, S. M. Moon, and S. B. Cho, “Robust Classifying BSR Noises Using Deep Learning Model based on GAN,” Journal of Korean Society  for Noise and Vibration Engineering (KSNVE), vol. 29, no. 3, pp. 11-17, 2019. (In Korean)  <br>
     - J. Y. Kim and S. B. Cho, “Evolutionary Optimization of Hyperparameters in Deep Learning Models,” IEEE  Congress on Evolutionary Computation (CEC), pp. 808-814, 2019.  <br>
     - J. Y. Kim and S. B. Cho, “Classifying Excavator Operations with Fusion Network of Multi-Modal Deep  Learning Models,” Int. Conf. on Soft Computing Models in Industrial and Environmental Applications (SOCO), pp. 25-34, 2019.   <br>
     - J. Y. Kim and S. B. Cho, “Electric Energy Consumption Prediction by Deep Learning with State  Explainable Autoencoder,” Energies, vol. 12, no. 4, pp. 739, 2019. (SCIE)(IF: 2.676)  <br>
     - J. Y. Kim and S. B. Cho, “A Method of Speech Commands Recognition with Transferred Encoder-decoder  GAN,” KIISE Trans. on Computing Practices (KTCP), vol. 25, no. 2, pp. 106-110, 2019. (In Korean)  <br>
     - J. Y. Kim and S. B. Cho, “A Latent Space Matching Model based on Deep Autoencoder for Reducing  Algorithmic Bias of Gender,” Korea Software Congress (KSC), pp. 719-721, 2018. (In Korean)  <br>
     - J. Y. Kim and S. B. Cho, “Detecting Intrusive Malware with a Hybrid Generative Deep Learning Model,”  Int. Conf. on Intelligent Data Engineering and Automated Learning (IDEAL), pp. 499-507, 2018.  <br>
     - J. Y. Kim and S. B. Cho, “A Method of Speech Commands Recognition with Transferred Encoder-decoder  GAN,” Korean Computer Congress (KCC), pp. 814-816, 2018. (In Korean)  <br>
     - J. Y. Kim, S. J. Bu, and S. B. Cho, “Hybrid Deep Learning based on GAN for Classifying BSR Noises  from Invehicle Sensors,” Int. Conf. on Hybrid Artificial Intelligence Systems (HAIS), pp. 27-38, 2018.  <br>
     - J. Y. Kim, S. J. Bu, and S. B. Cho, “Zero-day Malware Detection using Transferred Generative Adversarial  Networks,” Information Sciences, vol. 460, pp. 83-102, 2018. (SCI)(IF: 4.832)  <br>
     - J. Y. Kim, S. J. Bu, and S. B. Cho, “Malware Detection using Deep Transferred Generative Adversarial  Networks,” Int. Conf. on Neural Information Processing (ICONIP), pp. 556-564, 2017.  <br>
     - J. Y. Kim, S. J. Bu, and S. B. Cho, “A Method of Malware Detection with Deep Transfer-GAN,” Korea Computer Congress (KCC), pp. 1893-1895, 2017. (In Korean)  <br>




# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
