# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Jin-Young Kim
title: 김진영
email: jeremy@twelvelabs.io
# email_title: Email (Email title override)
# phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
website: https://github.com/seahl0119
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: never

# Social links
# twitter_username: jekyllrb
github_username:  seahl0119
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: profile.php?id=100009180653823
# flickr_username: jekyll
# instagram_username: jekyll
linkedin_username: jin-young-kim-4326a2233
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# orcid_username: 0000-0001-9691-877X
googlescholar_username: 7VupJX4AAAAJ

# # Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# # - title: another link
# #   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
# #   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
      J.-Y. Kim received a BS degree in mathematics and computer science from Yonsei University, Seoul, South Korea, in 2018. He is currently pursuing a Ph.D. degree at the Department of Computer Science, Yonsei University. 
      His current research interests include neural networks, artificial intelligence, and controllable representation learning.

      <strong> Research interest <strong>
      - Deep learning; diffusion model
      - Representation learning
      - Generative model
      - Video foundation model
      
# You can even add paragraphs by using empty lines like this and add anything else [markdown](https://www.markdownguide.org/getting-started#what-is-markdown) supports such as
#   - Lists
#   - Tables
#   - <a href="google.com">Links</a>
#   - Images ![alt text](/images/landscape-trees.jpg "Trees")

content:
          
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Twelvelabs
        sub_title: ML Research Scientist
        caption: 2023.10 - present
        link: https://www.twelvelabs.io/
        # quote: >
        #   Short description of the company (optional)
        # description: | # this will include new lines to allow paragraphs
        #   Description of role
        
      - title: Riiid Inc.
        sub_title: Senior AI Research Scientist
        caption: 2023.02- 2023.10
        # link: https://www.twelvelabs.io/
        
      - title: Riiid Inc.
        sub_title: AI Research Scientist
        caption: 2022.04-2023.02 
        # link: https://www.twelvelabs.io/

                
  - title: Education
    layout: list
    content:
      - layout: left
        title: Yonsei University, Korea
        sub_title: M. S. & Ph. D. Combined course student in Computer Science
        caption: 2018 - (GPA &#58; 4.16 / 4.30) 
        # link: https://www.twelvelabs.io/
                
      - title: Yonsei University, Korea
        sub_title: B.S. in Mathematics
        caption: 2014.03 - 2018.02 (GPA &#58; 3.59 / 4.30) 
                
      - title: Yonsei University, Korea
        sub_title: B.S. in Computer Science
        caption: 2014.03 - 2018.02 (GPA &#58; 3.59 / 4.30) 

        
  - title: Academic Experience
    layout: text
    content: | # this will include new lines to allow paragraphs
      - <strong> Introduction to Artificial Intelligence:</strong> Methods, Models, Algorithms, Int. Summer University 2018,  Higher School of Economics, 2018. 


        
  - title: Publications
    layout: text
    content: | # this will include new lines to allow paragraphs
     - Twelvelabs, “Pegasus-v1 Technical Report,” arXiv preprint, 2024.  
     - <strong> J. Y. Kim&#42;</strong>, H. Go&#42;, S. Kwon, and H. G. Kim, “Denoising Task Difficulty-based Curriculum for Training Diffusion Models,” arXiv preprint, 2024.  (&#42; Denotes equal contribution)  <br>
     - B. Park, H. Go, <strong> J. Y. Kim </strong> S. Woo, S. Ham, and C. Kim, “Switch Diffusion Transformer: Synergizing Denoising Tasks with Sparse Mixture-of-Experts,” arXiv preprint, 2024. <br>
     - S. Woo&#42;, B. Park&#42;, H. Go, <strong> J. Y. Kim </strong>, and C. Kim, “HarmonyView: Harmonizing Consistency and Diversity in One-Image-to-3D,” IEEE/CVF Conference on Computer Vision and Pattern Recognition (CVPR), 2024. (&#42; Denotes equal contribution)  <br>
     - B. Park&#42;, S. Woo&#42;, H. Go &#42;, <strong> J. Y. Kim&#42;</strong>, C. Kim, “Denoising Task Routing for Diffusion Models,” International Conference on Learning Representations (ICLR), 2024. (&#42; Denotes equal  contribution)  <br>
     - S. Kwon&#42;, S. Kim&#42;, S. Lee, <strong>J. Y. Kim</strong>, S. An, and K. Kim, “Addressing Selection Bias in Computerized Adaptive Testing: A User-Wise Aggregate Influence Function Approach,” International Conference on Information & Knowledge Management (CIKM), 2024. (&#42; Denotes equal  contribution)  <br>
     - Y. Lee&#42;, <strong>J. Y. Kim&#42;</strong>, H. Go&#42;, M Jeong, S. Oh, and S. Choi, “Multi-Architecture Multi-Expert Diffusion  Models,” AAAI Conference on Artificial Intelligence (AAAI), 2024. (&#42; Denotes equal  contribution)  <br>
     - <strong>J. Y. Kim&#42;</strong>, S. Kwon&#42;, H. Go&#42;, Y. Lee, and S. Choi, “ScoreCL: Augmentation-Adaptive Contrastive  Learning via Score-Matching Function,” arXiv preprint, 2024.  (&#42; Denotes equal contribution)  <br>
     - H. Go&#42;, <strong>J. Y. Kim&#42;</strong>, Y. Lee, S. Lee, S. Oh, H. Moon, and S. Choi, “Addressing Negative Transfer in  Diffusion Models,” Advances in Neural Information Processing Systems (NeurIPS), 2024. (&#42; Denotes equal contribution)  <br>
     - H. Go&#42;, Y. Lee&#42;, <strong>J. Y. Kim&#42;</strong>, S. Lee, M. Jeong, H. S. Lee, and S. Choi, “Towards Practical Plug-and-Play  Diffusion Models”, IEEE/CVF Conference on Computer Vision and Pattern Recognition (CVPR), 2023. (&#42; Denotes equal contribution)  <br>
     - <strong>J. Y. Kim</strong> and S. B. Cho, “Predicting Residential Energy Consumption by Explainable Deep Learning with  Long-term and Short-term Latent Variables,” Cybernetics and Systems, vol. 54, no. 3, pp. 270-285, 2023.  (SCIE) (IF: 1.879)  <br>
     - J. Park, <strong>J. Y. Kim</strong>, S. Kwon, and S. W. Lee, “SAICL: Student Modelling with Interaction-level Auxiliary  Contrastive Tasks for Knowledge Tracing and Dropout Prediction”, arXiv preprint arXiv:2210.09012,  2022.  <br>
     - <strong>J. Y. Kim</strong> and S. B. Cho, “An Information Theoretic Approach to Reducing Algorithmic Bias for Machine  Learning,” Neurocomputing, vol. 500, pp. 26-38, 2022. (SCIE) (IF: 5.719)  <br>
     - <strong>J. Y. Kim </strong>and S.-B. Cho, “Obfuscated Malware Detection Using Deep Generative Model based on  Global/Local Features,” Computers & Security, pp. 102501, 2022. (SCIE) (IF: 4.438)  <br>
     - <strong>J. Y. Kim </strong>and S.-B. Cho, “Explainable Prediction of Electric Energy Demand Using a Deep Autoencoder  with Interpretable Latent Space,” Expert Systems with Applications, vol. 186, pp. 115842, 2021. (SCIE)  (IF: 6.954)  <br>
     - G.-B. Jang, <strong>J.-Y. Kim</strong> and S.-B. Cho, "Cross-Domain Fault Diagnosis of Rotating Machinery Using  Discriminative Feature Attention Network," IEEE Access, vol. 9, pp. 99781 - 99793, 2021. (SCIE) (IF:  3.367)  <br>
     - <strong>J. Y. Kim</strong> and S.-B. Cho, "A Systematic Analysis and Guidelines of Graph Neural Networks for Practical  Applications," Expert Systems with Applications, 2021. (SCIE) (IF: 6.954)   <br>
     - S.-B. Cho and <strong>J. Y. Kim</strong>, "Clustered embedding using deep learning to analyze urban mobility based on  complex transportation data," PLoS one, vol. 16, no. 4, pp. e0249318, 2021. (SCIE) (IF: 3.240)  <br>
     - <strong>J. Y. Kim</strong> and S. B. Cho, “Deep CNN Transferred from VAE and GAN for Classifying Irritating Noise in  Automobile,” Neurocomputing, 2021. (SCIE)(IF: 5.719)   <br>
     - <strong>J. Y. Kim</strong> and S. B. Cho, “A Deep Neural Network Ensemble of Multimodal Signals for Classifying  Excavator Operations,” Neurocomputing, 2021. (SCIE)(IF: 5.719)  <br>
     - <strong>J. Y. Kim</strong> and S.-B. Cho, "Electric Energy Demand Forecasting with Explainable Time-series Modeling,"  Int. Conf. on Data Mining Workshop: BigData4SmartEnergy, 2020.   <br>
     - K.-H. Lim, <strong>J. Y. Kim</strong> and S.-B. Cho, "Generative Adversarial Network with Guided Generator for Non stationary Noise Cancelation," The 15th International Conference on Hybrid Artificial Intelligent Systems,  2020.  <br>
     - <strong>J.-Y. Kim</strong> and S.-B. Cho, "Interpretable Deep Learning with Hybrid Autoencoders to Predict Electric  Energy Consumption," Int. Workshop on Soft Computing Models in Industrial and Environmental  Applications, 2020  <br>
     - <strong>J.-Y. Kim</strong> and S.-B. Cho, “Fair Representation for Safe Artificial Intelligence via Adversarial Learning of  Unbiased Information Bottleneck.,” AAAI Conf. on Artificial Intelligence Workshop: SafeAI, 2020.  <br>
     - <strong>J. Y. Kim</strong>, K. H. Lim, and S. B. Cho, “Personalized POI Embedding for Successive POI Recommendation with Large-scale Smart Card Data,” IEEE Int. Conf. on Big Data, 2019.   <br>
     - <strong>J. Y. Kim</strong> and S. B. Cho, “Unsupervised Novelty Detection in Video with Adversarial Autoencoder based  on Non-Euclidean Space,” Int. Conf. on Signal Image Technology & Internet based Systems, 2019.  <br>
     - <strong>J. Y. Kim</strong> and S. B. Cho, “Conditioned Generative Model via Latent Semantic Controlling for Learning  Deep Representation of Data,” Int. Conf. on Intelligent Data Engineering and Automated Learning  (IDEAL), 2019.   <br>
     - K. H. Lim, <strong>J. Y. Kim</strong>, and S. B. Cho, “Non-stationary Noise Cancellation Using Deep Autoencoder based  on Adversarial Learning,” Int. Conf. on Intelligent Data Engineering and Automated Learning (IDEAL), 2019.  <br>
     - <strong>J. Y. Kim</strong> and S. B. Cho, “Evolutionary Optimization of Hyperparameters in Deep Learning Models,” IEEE  Congress on Evolutionary Computation (CEC), pp. 808-814, 2019.  <br>
     - <strong>J. Y. Kim</strong> and S. B. Cho, “Classifying Excavator Operations with Fusion Network of Multi-Modal Deep  Learning Models,” Int. Conf. on Soft Computing Models in Industrial and Environmental Applications (SOCO), pp. 25-34, 2019.   <br>
     - <strong>J. Y. Kim</strong> and S. B. Cho, “Electric Energy Consumption Prediction by Deep Learning with State  Explainable Autoencoder,” Energies, vol. 12, no. 4, pp. 739, 2019. (SCIE)(IF: 2.676)  <br>
     - <strong>J. Y. Kim</strong> and S. B. Cho, “Detecting Intrusive Malware with a Hybrid Generative Deep Learning Model,”  Int. Conf. on Intelligent Data Engineering and Automated Learning (IDEAL), pp. 499-507, 2018.  <br>
     - <strong>J. Y. Kim</strong>, S. J. Bu, and S. B. Cho, “Hybrid Deep Learning based on GAN for Classifying BSR Noises  from Invehicle Sensors,” Int. Conf. on Hybrid Artificial Intelligence Systems (HAIS), pp. 27-38, 2018.  <br>
     - <strong>J. Y. Kim</strong>, S. J. Bu, and S. B. Cho, “Zero-day Malware Detection using Transferred Generative Adversarial  Networks,” Information Sciences, vol. 460, pp. 83-102, 2018. (SCI)(IF: 4.832)  <br>
     - <strong>J. Y. Kim</strong>, S. J. Bu, and S. B. Cho, “Malware Detection using Deep Transferred Generative Adversarial  Networks,” Int. Conf. on Neural Information Processing (ICONIP), pp. 556-564, 2017.  <br>

  - title: Summary Of Research Contributions
    layout: text
    content: | # this will include new lines to allow paragraphs
      - International Journal Paper <strong> 11</strong>  included SCI(E) <strong> 11.</strong>   <br>
      - International Conference Paper <strong>  14 </strong>


  - title: Projects
    layout: text
    content: | # this will include new lines to allow paragraphs
      - 상대방의 감성을 추론, 판단하여 그에 맞추어 대화하고 대응할 수 있는 감성지능 기술연구개발(정보통신기획평가원)&#58;  <strong>Abusive sentence classification, algorithmic bias </strong>
      - BSR소음 분류의 잡음 강건성을 위한 GAN 딥러닝 모형(현대엔지비㈜)&#58; <strong>signal processing </strong>
      - Development of Hybrid Deep Learning Method to Detect Software Attacks (AOARD)&#58; <strong> malware detection </strong>
      - 굴삭기 프런트의 모션 데이터를 이용한 작업모드 분석 및 사용률 추출 기술 개발(두산인프라코어㈜)&#58; <strong>signal processing, video classification, multi-modal data </strong>
      - AI기반 건설기계 건정성 관리시스템(진단 밀 장비관리)개발 2단계(두산인프라코어㈜)&#58; <strong>signal processing, anomaly detection, domain adaptation </strong>
      - 실시간 영상DB 분석기술 개발(한국전자통신연구원)&#58; <strong>video anomaly detection </strong>
      - XAI(eXplainalb AI) 기반 스마트 에너지 플랫폼 기술 개발(한국과학기술원, KEPCO)&#58; <strong>energy consumption prediction, explainable AI </strong>
      - 교통이용내역 정보처리에 관한 연구(㈜에프에이솔루션)&#58; <strong>POI recommendation </strong>
      - 응급상황 전 단계 정보연계 복합지능 스마트 EMS 시스템 개발(정보통신산업진흥원)&#58; <strong>speech enhancement, speaker verification </strong>
      - GAN과 딥러닝 Transformer 기반 잡음제거 및 음성인식 엔진 개발&#58; <strong>speech enhancement </strong>
      - 라이프로그 패턴발견을 위한 그래프 임베딩 기술 연구(한국전자통신연구원)&#58; <strong>graph embedding </strong>
      - 그래프 라이프로그로 분석을 위한 뉴로-심볼릭 결합기술 연구(한국전자통신연구원)&#58;  <strong>graph classification, graph embedding </strong>



  - title: Patents
    layout: text
    content: | # this will include new lines to allow paragraphs
      - 국내 출원, 형태소 정보를 추가한 딥러닝 기반 자동 대화생성 방법, 10-2018-0073153, 2018. 
      - 국내 출원, 편향성이 감소된 분류장치 및 방법, 10-2019-0005334, 2019. 
      - 해외 출원, 편향성이 감소된 분류장치 및 방법, PCT/KR2019/002698, 2019. 
      - 국내 출원, 기계학습 기반의 화자 분리 방법 및 그를 위한 장치, 10-2019-0141938, 2019. 
      - 국내 출원, 기계학습 기반의 잡음 제거 방법 및 그를 위한 장치, 10-2020-0084272, 2020. 
      - 국내 등록, 편향성이 감소된 분류장치 및 방법, 10-2198461, 2020. 
      - 국내 등록, 기계학습 기반의 화자 분리 방법 및 그를 위한 장치, 10-2313387, 2021. 


  - title: Professional Service 
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Conference reviewer&#58;  NeurIPS, ICML, CVPR, IEEE WCCI 
      - Journal reviewer&#58;  IEEE Trans. on Neural Network and Learning Systems, IEEE Trans. on Cybernetics, Computing Survey, IEEE Trans. on Emerging Topics in Computational Intelligence, IEEE Access, Computer &#38;  Security, Knowledge-Based Systems 




  - title: Citations
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Just Google scholar pulls out a list of 784 citations. <strong> (h-index: 12) </strong>


  - title: Professional Recognition
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Academic Award, Korean Institute of Intelligent Systems (KIIS), 2018. 
      - Global Ph.D. Fellowship, National Research Foundation of Korea (NRF), (March 2019. – February 2021.) Naver Ph.D. Fellowship, 2022 



  - title: Paper Awards
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Best Student Paper Award, Korea Computer Congress (KCC’17), 2017. 
      - Best Paper Award, BSR improvements research contest Hyundai motors, 2017. 
      - Paper Award, Int. Military Science and Technology Fair, 2018. 
      - Best Session Presentation Award, Korea Computer Congress (KCC’18), 2018. 
      - Best Paper Award, Korea Software Congress (KSC’ 18), 2018. 
      - Academic Paper Award, Yonsei University, 2019. 
      - Best Paper Award, Korean Institute of Intelligent Systems Fall Conf, 2019. 
      - Academic Paper Award, Yonsei University, 2019. 
      - Best Paper Award, Korea Software Congress (KSC’ 19), 2019. 
      - Best Session Presentation Award, Korea Computer Congress (KCC’19), 2019. 
      - Best Paper Award, Korea Computer Congress (KCC’20), 2020. 
      - Best Session Presentation Award, Korea Software Congress (KSC’ 21), 2021 
      - Best Session Presentation Award, Korea Software Congress (KSC’ 21), 2021 


  - title: Lectures, Talks, and Tutorials
    layout: text
    content: | # this will include new lines to allow paragraphs
      - <strong> Lecture</strong>, Python 전처리, 삼성전자, 2023
      - <strong> Lecture</strong>, 데이터 사이언스 논문 세미나: 생성 모델(Generative model)의 이해와 VAE, GAN을 이용한 선택적 생성, 패스트캠퍼스, 2019 
      - <strong> Invited Speaker (presentation material)</strong>, Int. Conf. on Neural Information Processing, 2019 
      - <strong> Invited Speaker (presentation material)</strong>, IEEE Int. Conf. on Big Data and Smart Computing, 2020 
      - <strong> Lecture</strong>, Data Representation, CSI7103-01 (인공지능특강), Yonsei University, 2020. 
      - <strong> Lecture</strong>, 인공지능과 딥러닝 교육과정, 산업기술진흥협회, 2019. 
      - <strong> Lecture</strong>, 2019년 삼성전자 데이터 역량강화 공통트랙: 데이터 마이닝, 삼성전자, 2019. Lecture, 인공지능과 딥러닝 교육과정, 산업기술진흥협회, 2020. 
      - <strong> Lecture</strong>, 2019년 삼성전자 데이터 역량강화 공통트랙: 데이터 마이닝, 삼성전자, 2020. 
      - <strong> Invited Speaker (presentation material)</strong>, Int. Conf. on Biologically Inspired Techniques in Many Criteria Decision Making, 2021












# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
